---
- hosts: vm
  roles:
    - swap

- hosts: all
  gather_facts: no
  roles:
    - { role: apt_proxy, when: use_apt_proxy }
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

- hosts: mysql
  roles:
    - mysql


- hosts: application
  handlers:
    - include: roles/delayed_job/handlers/main.yml
  roles:
    - base
    - { role: ruby, tags: ruby }
    - vim
    - webserver

- hosts: delayed_job
  handlers:
    - include: roles/passenger/handlers/main.yml
  roles:
    - base
    - ruby
    - { role: delayed_job, tags: delayed_job }

